{{!-- Used in: data-table/data-table-content --}}
{{yield (hash
    isLoading=@dataTable.isLoading
    content=@content
    offset=this.offset
    enableLineNumbers=@enableLineNumbers
    hasClickRowAction=(and (or @onClickRow @rowLink) true)
    toggleSelected=this.updateSelection
    selection=@dataTable.selection
    enableSelection=@enableSelection
    linkedRoutes=@linkedRoutes
    rowLink=@rowLink
    rowLinkModelProperty=@rowLinkModelProperty
    noDataMessage=@noDataMessage
    fields=@fields
    Row=(component "data-table/row"
      dataTable=@dataTable
      enableLineNumbers=@enableLineNumbers
      enableSelection=@enableSelection
      selectionProperty=@selectionProperty
      selection=@dataTable.selection
      offset=this.offset
      hasClickRowAction=(and (or @onClickRow @rowLink) true)
      onClickRow=@onClickRow
      linkedRoutes=@linkedRoutes
      rowLink=@rowLink
      rowLinkModelProperty=@rowLinkModelProperty
      fields=@fields
      toggleSelected=this.updateSelection))}}
